on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        fetch-depth: 0
    - uses: step-security/changed-files@v47
      id: changed-files
      with:
        files: '**/*.md'
        separator: ","
    - uses: ./
      if: steps.changed-files.outputs.any_changed == 'true'
      with:
        globs: ${{ steps.changed-files.outputs.all_changed_files }}
        separator: ","
