name: Checkers

on:
  pull_request:
  push:
    branches-ignore:
      - 'dependabot/**'
  workflow_dispatch:

jobs:

  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - run: 'npx linkinator "*.md" --directory-listing --skip "^https://wikipedia.org/"'

  spellcheck:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@v2
      with:
        egress-policy: audit

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: tbroadley/spellchecker-cli-action@8369e98753c0d2c3a3c76fb4519d9056d1d4b129 # v1.1.1
      with:
        dictionaries: '.github/dictionary.txt'
        files: '*.md'
